create extension if not exists pgcrypto;

create table if not exists public.live_events (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  title text not null,
  description text,
  speaker text,
  cover_url text,
  scheduled_at timestamptz,
  actual_start_at timestamptz,
  actual_end_at timestamptz,
  status text not null default 'draft' check (status in ('draft', 'scheduled', 'rehearsal', 'live', 'interrupted', 'finished', 'archived')),
  visibility text not null default 'public' check (visibility in ('public', 'private')),
  mux_live_stream_id text unique,
  mux_playback_id text,
  replay_asset_id text,
  replay_playback_id text,
  social_fallback_url text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.live_destinations (
  id uuid primary key default gen_random_uuid(),
  live_event_id uuid not null references public.live_events(id) on delete cascade,
  platform text not null check (platform in ('mux', 'youtube', 'facebook', 'tiktok', 'instagram', 'custom')),
  enabled boolean not null default false,
  credential_ref text,
  target_url_ref text,
  state text not null default 'disabled' check (state in ('disabled', 'ready', 'connecting', 'live', 'error', 'unavailable', 'stopped')),
  last_error text,
  started_at timestamptz,
  stopped_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (live_event_id, platform)
);

create table if not exists public.live_session_logs (
  id bigint generated by default as identity primary key,
  event_id uuid not null references public.live_events(id) on delete cascade,
  destination_id uuid references public.live_destinations(id) on delete set null,
  level text not null default 'info' check (level in ('debug', 'info', 'warning', 'error')),
  code text,
  message text not null,
  metadata_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.media_assets (
  id uuid primary key default gen_random_uuid(),
  type text not null check (type in ('sermon', 'livestream', 'podcast', 'clip', 'audio', 'video')),
  provider text not null,
  provider_asset_id text,
  title text not null,
  description text,
  speaker text,
  series text,
  tags text[] not null default '{}',
  duration integer,
  thumbnail_url text,
  playback_url text,
  published_at timestamptz,
  visibility text not null default 'public' check (visibility in ('public', 'private')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.radio_programs (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  host text,
  description text,
  artwork_url text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.radio_schedule (
  id uuid primary key default gen_random_uuid(),
  program_id uuid not null references public.radio_programs(id) on delete cascade,
  weekday smallint not null check (weekday between 0 and 6),
  start_time time not null,
  end_time time not null,
  priority integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  check (end_time > start_time)
);

create table if not exists public.radio_recordings (
  id uuid primary key default gen_random_uuid(),
  program_id uuid references public.radio_programs(id) on delete set null,
  source_url text not null,
  duration integer,
  recorded_at timestamptz not null,
  media_asset_id uuid references public.media_assets(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  actor_user_id uuid references auth.users(id) on delete set null,
  action text not null,
  entity text not null,
  entity_id uuid,
  metadata_json jsonb not null default '{}'::jsonb,
  ip_hash text,
  created_at timestamptz not null default now()
);

create index if not exists live_events_public_status_idx on public.live_events (visibility, status, scheduled_at);
create index if not exists live_destinations_event_idx on public.live_destinations (live_event_id);
create index if not exists live_logs_event_created_idx on public.live_session_logs (event_id, created_at desc);
create index if not exists media_assets_public_idx on public.media_assets (visibility, published_at desc);
create index if not exists radio_schedule_day_idx on public.radio_schedule (weekday, start_time);
create index if not exists audit_logs_entity_idx on public.audit_logs (entity, entity_id, created_at desc);

create or replace function public.set_media_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists live_events_set_updated_at on public.live_events;
create trigger live_events_set_updated_at before update on public.live_events for each row execute function public.set_media_updated_at();
drop trigger if exists live_destinations_set_updated_at on public.live_destinations;
create trigger live_destinations_set_updated_at before update on public.live_destinations for each row execute function public.set_media_updated_at();
drop trigger if exists media_assets_set_updated_at on public.media_assets;
create trigger media_assets_set_updated_at before update on public.media_assets for each row execute function public.set_media_updated_at();
drop trigger if exists radio_programs_set_updated_at on public.radio_programs;
create trigger radio_programs_set_updated_at before update on public.radio_programs for each row execute function public.set_media_updated_at();

alter table public.live_events enable row level security;
alter table public.live_destinations enable row level security;
alter table public.live_session_logs enable row level security;
alter table public.media_assets enable row level security;
alter table public.radio_programs enable row level security;
alter table public.radio_schedule enable row level security;
alter table public.radio_recordings enable row level security;
alter table public.audit_logs enable row level security;

create policy "public can read published live events" on public.live_events for select using (visibility = 'public' and status in ('scheduled', 'live', 'interrupted', 'finished', 'archived'));
create policy "public can read published media" on public.media_assets for select using (visibility = 'public' and published_at is not null);
create policy "public can read active radio programs" on public.radio_programs for select using (active = true);
create policy "public can read active radio schedule" on public.radio_schedule for select using (active = true);

create policy "admins manage live events" on public.live_events for all to authenticated using ((auth.jwt() ->> 'role') in ('admin', 'superadmin')) with check ((auth.jwt() ->> 'role') in ('admin', 'superadmin'));
create policy "admins manage destinations" on public.live_destinations for all to authenticated using ((auth.jwt() ->> 'role') in ('admin', 'superadmin')) with check ((auth.jwt() ->> 'role') in ('admin', 'superadmin'));
create policy "admins read live logs" on public.live_session_logs for select to authenticated using ((auth.jwt() ->> 'role') in ('admin', 'superadmin'));
create policy "admins manage media" on public.media_assets for all to authenticated using ((auth.jwt() ->> 'role') in ('admin', 'superadmin', 'editor')) with check ((auth.jwt() ->> 'role') in ('admin', 'superadmin', 'editor'));
create policy "radio staff manage programs" on public.radio_programs for all to authenticated using ((auth.jwt() ->> 'role') in ('admin', 'superadmin', 'radio_dj')) with check ((auth.jwt() ->> 'role') in ('admin', 'superadmin', 'radio_dj'));
create policy "radio staff manage schedule" on public.radio_schedule for all to authenticated using ((auth.jwt() ->> 'role') in ('admin', 'superadmin', 'radio_dj')) with check ((auth.jwt() ->> 'role') in ('admin', 'superadmin', 'radio_dj'));
create policy "radio staff manage recordings" on public.radio_recordings for all to authenticated using ((auth.jwt() ->> 'role') in ('admin', 'superadmin', 'radio_dj')) with check ((auth.jwt() ->> 'role') in ('admin', 'superadmin', 'radio_dj'));
create policy "admins read audit logs" on public.audit_logs for select to authenticated using ((auth.jwt() ->> 'role') in ('admin', 'superadmin'));

comment on column public.live_destinations.credential_ref is 'Reference to a server-side secret. Never store a stream key in this table.';
comment on column public.live_destinations.target_url_ref is 'Reference to server-side relay configuration, not a public ingest URL.';
